# Generated by Django 5.0.3 on 2024-03-19 01:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="updated_at",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
