name: Django CI Workflow

on: [pull_request]

jobs:
  pytest:
    runs-on: ubuntu-latest # os for running the job
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: '**/requirements.txt'

      - name: Install Requirements
        run: pip install -r ./requirements.txt

      - name: Pytest
        run: pytest --create-db -x
